// Command simulator runs the Fleet agent simulator against an upstream management cluster.
package main

import (
	"context"
	"flag"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"

	fleet "github.com/rancher/fleet/pkg/apis/fleet.cattle.io/v1alpha1"

	"github.com/rancher/fleet/agent-simulator/pkg/chaos"
	"github.com/rancher/fleet/agent-simulator/pkg/config"
	_ "github.com/rancher/fleet/agent-simulator/pkg/metrics" // register Prometheus metrics
	"github.com/rancher/fleet/agent-simulator/pkg/simulator"

	"github.com/prometheus/client_golang/prometheus/promhttp"
	"golang.org/x/sync/errgroup"
	"go.uber.org/zap/zapcore"
	"k8s.io/apimachinery/pkg/runtime"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
	ctrlmetrics "sigs.k8s.io/controller-runtime/pkg/metrics"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
)

var (
	scheme = runtime.NewScheme()
)

func init() {
	utilruntime.Must(clientgoscheme.AddToScheme(scheme))
	utilruntime.Must(fleet.AddToScheme(scheme))
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	var (
		configPath  string
		kubeconfig  string
		logLevel    int
		metricsAddr string
		dryRun      bool
	)

	flag.StringVar(&configPath, "config", "config.yaml", "Path to simulator config YAML")
	// --kubeconfig may already be registered by controller-runtime's init; guard against the panic.
	if flag.Lookup("kubeconfig") == nil {
		flag.StringVar(&kubeconfig, "kubeconfig", "", "Path to kubeconfig (overrides KUBECONFIG env and config file)")
	}
	flag.IntVar(&logLevel, "log-level", 0, "Log verbosity (0=info, 1=debug, higher values increase verbosity)")
	flag.StringVar(&metricsAddr, "metrics-addr", ":9090", "Metrics bind address (set to '0' to disable)")
	flag.BoolVar(&dryRun, "dry-run", false, "Log status updates without sending any API patches")
	flag.Parse()

	// If we didn't register the flag ourselves, read whatever value was set.
	if kubeconfig == "" {
		if f := flag.Lookup("kubeconfig"); f != nil {
			kubeconfig = f.Value.String()
		}
	}
	// Fall back to KUBECONFIG env.
	if kubeconfig == "" {
		kubeconfig = os.Getenv("KUBECONFIG")
	}

	// Configure zap log level: 0=Info, 1=Debug, higher values are more verbose.
	zapLevel := zapcore.Level(-logLevel)
	logf.SetLogger(zap.New(zap.Level(&zapLevel)))
	logger := logf.Log.WithName("simulator")

	cfg, err := config.Load(configPath)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	if kubeconfig != "" {
		cfg.Kubeconfig = kubeconfig
	}
	if err := cfg.Validate(); err != nil {
		return fmt.Errorf("invalid config: %w", err)
	}

	// In multi-cluster mode each cluster entry typically carries its own kubeconfig
	// (generated by create-cluster). Only build a global REST config when one is
	// explicitly provided or when running in single-cluster mode.
	var restCfg *rest.Config
	if cfg.Kubeconfig != "" || len(cfg.Clusters) == 0 {
		var err error
		restCfg, err = clientcmd.BuildConfigFromFlags("", cfg.Kubeconfig)
		if err != nil {
			return fmt.Errorf("building kubeconfig: %w", err)
		}
	}

	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer cancel()

	// Start the Prometheus metrics server unless disabled.
	if metricsAddr != "" && metricsAddr != "0" {
		mux := http.NewServeMux()
		mux.Handle("/metrics", promhttp.HandlerFor(ctrlmetrics.Registry, promhttp.HandlerOpts{}))
		srv := &http.Server{Addr: metricsAddr, Handler: mux}
		go func() {
			logger.Info("Starting metrics server", "addr", metricsAddr)
			if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
				logger.Error(err, "metrics server error")
			}
		}()
		defer func() { _ = srv.Close() }()
	}

	if dryRun {
		logger.Info("Dry-run mode enabled: status patches will be logged but not sent")
	}

	if len(cfg.Clusters) > 0 {
		logger.Info("Starting multi-cluster simulator", "clusterCount", len(cfg.Clusters))
		return runMultiCluster(ctx, cfg, restCfg, dryRun)
	}

	logger.Info("Starting simulator",
		"cluster", cfg.ClusterName,
		"clusterNamespace", cfg.ClusterNamespace,
		"heartbeatInterval", cfg.HeartbeatInterval,
		"resourceCount", cfg.ResourceCount,
		"dryRun", dryRun,
	)
	return runSingleCluster(ctx, cfg, restCfg, true, dryRun)
}

// runSingleCluster starts a single simulator manager for the given config.
// skipNameValidation should be true when running multiple managers in the same process.
func runSingleCluster(ctx context.Context, cfg *config.Config, restCfg *rest.Config, skipNameValidation bool, dryRun bool) error {
	mgr, err := simulator.NewManager(restCfg, scheme, simulator.Options{
		ClusterNamespace:      cfg.ClusterNamespace,
		BDNamespace:           cfg.BDNamespace,
		ClusterName:           cfg.ClusterName,
		AgentNamespace:        cfg.AgentNamespace,
		ResourceCount:         cfg.ResourceCount,
		HeartbeatInterval:     cfg.HeartbeatInterval,
		HeartbeatInitialDelay: cfg.InitialDelay,
		RolloutSteps:          cfg.RolloutSteps,
		RolloutInterval:       cfg.RolloutInterval,
		SkipNameValidation:    skipNameValidation,
		DryRun:                dryRun,
		DriftEnabled:          cfg.Drift.Enabled,
		Drift: chaos.DriftOptions{
			AffectedResourceCount: cfg.Drift.ResourceCount,
			MinInterval:           cfg.Drift.MinInterval,
			MaxInterval:           cfg.Drift.MaxInterval,
			AffectsReady:          cfg.Drift.AffectsReady,
			AutoRecover:           cfg.Drift.AutoRecover,
			RecoveryDelay:         cfg.Drift.RecoveryDelay,
		},
		FailureEnabled: cfg.Failure.Enabled,
		Failure: chaos.FailureOptions{
			AffectedResourceCount: cfg.Failure.ResourceCount,
			MinInterval:           cfg.Failure.MinInterval,
			MaxInterval:           cfg.Failure.MaxInterval,
			Probability:           cfg.Failure.Probability,
			AutoRecover:           cfg.Failure.AutoRecover,
			RecoveryDelay:         cfg.Failure.RecoveryDelay,
		},
	})
	if err != nil {
		return fmt.Errorf("creating simulator manager: %w", err)
	}
	return mgr.Start(ctx)
}

// runMultiCluster starts one simulator manager per cluster entry, all sharing
// the same upstream REST config and running concurrently. A context cancellation
// (e.g. SIGINT) stops all managers.
func runMultiCluster(ctx context.Context, cfg *config.Config, restCfg *rest.Config, dryRun bool) error {
	logger := logf.Log.WithName("simulator")
	g, ctx := errgroup.WithContext(ctx)

	for _, cc := range cfg.Clusters {
		resolved := cc.Resolve(*cfg)

		// Each cluster may have its own kubeconfig (typical when create-cluster
		// generated separate ServiceAccount credentials per cluster). Build a
		// dedicated restCfg when the resolved kubeconfig differs from the global one.
		clusterRestCfg := restCfg
		if resolved.Kubeconfig != cfg.Kubeconfig {
			var err error
			clusterRestCfg, err = clientcmd.BuildConfigFromFlags("", resolved.Kubeconfig)
			if err != nil {
				return fmt.Errorf("building kubeconfig for cluster %s: %w", resolved.ClusterName, err)
			}
		} else if clusterRestCfg == nil {
			return fmt.Errorf("cluster %s: no kubeconfig — set kubeconfig per cluster entry or at the top level", resolved.ClusterName)
		}

		logger.Info("Starting cluster simulator",
			"cluster", resolved.ClusterName,
			"clusterNamespace", resolved.ClusterNamespace,
			"bdNamespace", resolved.BDNamespace,
		)
		g.Go(func() error {
			if err := runSingleCluster(ctx, &resolved, clusterRestCfg, true, dryRun); err != nil {
				return fmt.Errorf("cluster %s: %w", resolved.ClusterName, err)
			}
			return nil
		})
	}

	return g.Wait()
}
