kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: simpleapplabels
  namespace: {{.ProjectNamespace}}
  labels:
    team: one

spec:
  repo: https://github.com/rancher/fleet-test-data
  branch: master
  paths:
  - simple

  targetNamespace: {{.TargetNamespace}}

  targets:
  - name: test
    clusterSelector:
      matchLabels:
        envlabels: test
