apiServerCA: |-
  -----BEGIN CERTIFICATE-----
  MIIBVzCB/qADAgECAgEAMAoGCCqGSM49BAMCMCMxITAfBgNVBAMMGGszcy1zZXJ2
  ZXItY2FAMTU5ODAzMDYyMzAeFw0yMDA4MjExNzIzNDNaFw0zMDA4MTkxNzIzNDNa
  MCMxITAfBgNVBAMMGGszcy1zZXJ2ZXItY2FAMTU5ODAzMDYyMzBZMBMGByqGSM49
  AgEGCCqGSM49AwEHA0IABDHKZIafRCXRq+tRowJ5yR8LCg8Cc/mh8VorTG4focTG
  luOjmaaiYjFGz0Ck4JPffrW0TZrvKDIX+3rBDtk+tmWjIzAhMA4GA1UdDwEB/wQE
  AwICpDAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0gAMEUCIAjPm+V9iBNn
  ywca9cR/AFIavdlRrUjai/dY2mRcYhs9AiEA1pWWyqcT7ACX9v0KmVsOi/EKLxMJ
  QT33NgiIfaNsdcM=
  -----END CERTIFICATE-----
apiServerURL: https://172.17.0.1:6443
clusterNamespace: fleet-local
token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjVRdHRIejdaUk5TLW1HSmJRejFMVFRZaV9mMzQwdmEyVWNUaGNVMllHZTQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJmbGVldC1sb2NhbCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJpbXBvcnQtdG9rZW4tbG9jYWwtNmU1YmM4Y2EtY2U1Mi00OGQyLTk4MDktMTJjY2U4MjAwOTFkLXRvNTlnOXQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiaW1wb3J0LXRva2VuLWxvY2FsLTZlNWJjOGNhLWNlNTItNDhkMi05ODA5LTEyY2NlODIwMDkxZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjNlY2I3M2VhLWEzZDYtNGQxYi04NGUzLThlNTAyNjBmNGMxNSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpmbGVldC1sb2NhbDppbXBvcnQtdG9rZW4tbG9jYWwtNmU1YmM4Y2EtY2U1Mi00OGQyLTk4MDktMTJjY2U4MjAwOTFkIn0.UqtXqt7X9bTagPwSPXbuSvzb-aKUAA2A4IpROuL7eCGMMkezuf67jXg1pDasXDa5X_8IOeD3ge1L9X5x07BPuf49k9YaOLvnxxLq1fIt_YARiXylF_wdu3qx2GXQau0ewvF4c0ufyYdLMlPnNkz0WEkaRHi9gb6sBcokpBgwsuAS7kWDXGYEAcm0hhgsZmdGVWCdqltAfPfegY_BlrJCcuncnIEsXlyCuDBcSpEUJ76DPLK5CojfhTK27ijiEHr7LZnnLioxiV4CV4fpiyZCEonWfNlQle23fPQ67U4ThXoJl87Nc6A7muYg0K0yM6ANx2F_jWCPz65FIgxR7sBOyA
labels:
  foo: bar
