{{ $shards := list "" }}
{{ if .Values.shards }}
{{ $shards = concat $shards .Values.shards | uniq }}
{{ end }}
{{ range $shards }}
{{- if $.Values.gitops.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "gitjob{{if . }}-shard-{{ . }}{{end}}"
spec:
  selector:
    matchLabels:
      app: "gitjob"
  template:
    metadata:
      labels:
        app: "gitjob"
        fleet.cattle.io/shard-id: "{{ . }}"
        {{- if empty . }}
        fleet.cattle.io/shard-default: "true"
        {{- end }}
    spec:
      serviceAccountName: gitjob
      containers:
        - image: "{{ template "system_default_registry" $ }}{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          name: gitjob
          {{- if $.Values.metrics.enabled }}
          ports:
          - containerPort: 8081
            name: metrics
          {{- end }}
          args:
          - fleetcontroller
          - gitjob
          - --gitjob-image
          - "{{ template "system_default_registry" $ }}{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          {{- if $.Values.debug }}
          - --debug
          {{- end }}
          {{- if . }}
          - --shard-id
          - {{ quote . }}
          {{- end }}
          {{- if not $.Values.metrics.enabled }}
          - --disable-metrics
          {{- end }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- if $.Values.proxy }}
            - name: HTTP_PROXY
              value: {{ $.Values.proxy }}
            - name: HTTPS_PROXY
              value: {{ $.Values.proxy }}
            - name: NO_PROXY
              value: {{ $.Values.noProxy }}
          {{- end }}
          {{- if $.Values.controller.reconciler.workers.gitrepo }}
            - name: GITREPO_RECONCILER_WORKERS
              value: {{ quote $.Values.controller.reconciler.workers.gitrepo }}
          {{- end }}
          {{- if $.Values.debug }}
            - name: CATTLE_DEV_MODE
              value: "true"
          {{- else }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
                drop:
                - ALL
          {{- end }}
{{- if $.Values.extraEnv }}
{{ toYaml $.Values.extraEnv | indent 12}}
{{- end }}
      nodeSelector: {{ include "linux-node-selector" . | nindent 8 }}
{{- if $.Values.nodeSelector }}
{{ toYaml $.Values.nodeSelector | indent 8 }}
{{- end }}
      tolerations: {{ include "linux-node-tolerations" . | nindent 8 }}
{{- if $.Values.tolerations }}
{{ toYaml $.Values.tolerations | indent 8 }}
{{- end }}
      {{- if $.Values.priorityClassName }}
      priorityClassName: "{{$.Values.priorityClassName}}"
      {{- end }}

{{- if not $.Values.debug }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
{{- end }}
{{- end }}
---
{{- end }}
