apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-controller

{{- if not .Values.bootstrap.disabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-controller-bootstrap
{{- end }}
