kind: ConfigMap
apiVersion: v1
metadata:
  name: fleet-agent
data:
  config: |-
    {
      {{ if .Values.global.fleet.clusterLabels }}
      "labels":{{toJson .Values.global.fleet.clusterLabels}},
      {{ end }}
      {{ if .Values.labels }}
      "labels":{{toJson .Values.labels}},
      {{ end }}
      "clientID":"{{.Values.clientID}}"
    }
