apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-agent-simulator
spec:
  selector:
    matchLabels:
      app: fleet-agent-simulator
  template:
    metadata:
      labels:
        app: fleet-agent-simulator
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: '{{ template "system_default_registry" . }}{{.Values.image.repository}}:{{.Values.image.tag}}'
        arguments:
        - "--simulators={{.Values.simulators}}"
        name: fleet-agent-simulator
      serviceAccountName: fleet-agent
