name: Test Typos
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Check spelling of file.txt
      # Using v1.19.0 as v1.20.1 introduced a new false positive.
      # 'ro' in ${PWD}:${PWD}:ro was identified as a typo for 'to'
      uses: crate-ci/typos@v1.19.0

